return {
  -- {
  --   "saghen/blink.cmp",
  --   enabled = false,
  --   opts = {
  --     sources = {
  --       providers = {
  --         snippets = {
  --           opts = {
  --             extended_filetypes = {
  --               typescript = { "javascript" },
  --               typescriptreact = { "javascriptreact" },
  --               vue = { "typescript", "javascript" },
  --             },
  --           },
  --         },
  --       },
  --     },
  --   },
  -- },
}
