return {
  -- {
  --   "folke/which-key.nvim",
  --   opts = {
  --     defaults = {
  --       ["<leader>d"] = { name = "+debug" },
  --       ["<leader>dap"] = { name = "+python" },
  --       ["<leader>dag"] = { name = "+go" },
  --     },
  --   },
  -- },
  -- {
  --   "rcarriga/nvim-dap-ui",
  --   opts = {
  --     layouts = {
  --       {
  --         elements = {
  --           {
  --             id = "scopes",
  --             size = 0.25, -- Can be float or integer > 1
  --           },
  --           { id = "breakpoints", size = 0.25 },
  --           { id = "stacks", size = 0.25 },
  --           { id = "watches", size = 0.25 },
  --         },
  --         size = 40,
  --         position = "left", -- Can be "left" or "right"
  --       },
  --       {
  --         elements = {
  --           "repl",
  --         },
  --         size = 10,
  --         position = "bottom", -- Can be "bottom" or "top"
  --       },
  --       {
  --         elements = {
  --           "console",
  --         },
  --         size = 10,
  --         position = "bottom", -- Can be "bottom" or "top"
  --       },
  --     },
  --   },
  -- },
  -- {
  --   "mfussenegger/nvim-dap-python",
  --   keys = {
  --     {
  --       "<leader>dapm",
  --       function()
  --         require("dap-python").test_method()
  --       end,
  --       desc = "Test method",
  --     },
  --     {
  --       "<leader>dapc",
  --       function()
  --         require("dap-python").test_class()
  --       end,
  --       desc = "Test class",
  --     },
  --     {
  --       "<leader>daps",
  --       function()
  --         require("dap-python").debug_selection()
  --       end,
  --       desc = "Debug selection",
  --     },
  --   },
  --   config = function()
  --     require("dap-python").setup()
  --   end,
  -- },
  -- {
  --   "leoluz/nvim-dap-go",
  --   keys = {
  --     {
  --       "<leader>dagt",
  --       function()
  --         require("dap-go").debug_test()
  --       end,
  --       desc = "Test method",
  --     },
  --   },
  --   opts = {},
  -- },
}
